/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_ingriddominguez;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1234
 */
public class Main_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Main_Principal
     */
    public Main_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        pop_opciones = new javax.swing.JPopupMenu();
        jmi_elimina = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_nombreP = new javax.swing.JMenuItem();
        jmi_temperatura = new javax.swing.JMenuItem();
        jmi_superficie = new javax.swing.JMenuItem();
        jmi_distancia = new javax.swing.JMenuItem();
        pop_opcionesA = new javax.swing.JPopupMenu();
        jmi_EliminarA = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmi_nombre = new javax.swing.JMenuItem();
        jmi_nacionalidad = new javax.swing.JMenuItem();
        jmi_sueldo = new javax.swing.JMenuItem();
        jmi_peso = new javax.swing.JMenuItem();
        jmi_experiencia = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jp_planeta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombrePlaneta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jsp_temperatura = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        anillosSi = new javax.swing.JRadioButton();
        anillosNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tf_superficie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jsp_distancia = new javax.swing.JSpinner();
        btn_guardarPLaneta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreAstronauta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nacionalidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_sueldo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_experiencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sexoF = new javax.swing.JRadioButton();
        SexoM = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        btn_guardarAstronauta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_serie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcb_planeta = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jsp_velocidad = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jsp_peso = new javax.swing.JSpinner();
        btn_sonda = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tf_lugarDespeje = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jcb_astronautas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jcb_asAgregados = new javax.swing.JComboBox<>();
        btn_tripulada = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_planetas = new javax.swing.JTable();
        btn_listarPlanetas = new javax.swing.JButton();
        btn_ListarAstronautas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_astronautas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jcb_naveExpedicion = new javax.swing.JComboBox<>();
        btn_Iniciar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jpb_ida = new javax.swing.JProgressBar();
        jLabel28 = new javax.swing.JLabel();
        jpb_regreso = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jmi_elimina.setText("Eliminar");
        jmi_elimina.setToolTipText("");
        jmi_elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminaActionPerformed(evt);
            }
        });
        pop_opciones.add(jmi_elimina);

        jMenu2.setText("Modificar");

        jmi_nombreP.setText("Nombre");
        jmi_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nombrePActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_nombreP);

        jmi_temperatura.setText("Temperatura");
        jmi_temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_temperaturaActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_temperatura);

        jmi_superficie.setText("Superficie");
        jmi_superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_superficieActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_superficie);

        jmi_distancia.setText("Distancia");
        jmi_distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_distanciaActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_distancia);

        pop_opciones.add(jMenu2);

        jmi_EliminarA.setText("Eliminar");
        jmi_EliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_EliminarAActionPerformed(evt);
            }
        });
        pop_opcionesA.add(jmi_EliminarA);

        jMenu1.setText("MODIFICAR");

        jmi_nombre.setText("Nombre");
        jmi_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nombreActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_nombre);

        jmi_nacionalidad.setText("Nacionalidad");
        jmi_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nacionalidadActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_nacionalidad);

        jmi_sueldo.setText("Sueldo");
        jmi_sueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_sueldoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_sueldo);

        jmi_peso.setText("Peso");
        jmi_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pesoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_peso);

        jmi_experiencia.setText("Experiencia");
        jmi_experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_experienciaActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_experiencia);

        pop_opcionesA.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setText("Bienvenido!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear Planeta");

        jLabel2.setText("Nombre");

        jLabel3.setText("Temperatura");

        jsp_temperatura.setModel(new javax.swing.SpinnerNumberModel());

        jLabel4.setText("Anillos");

        grupo1.add(anillosSi);
        anillosSi.setSelected(true);
        anillosSi.setText("Si");

        grupo1.add(anillosNo);
        anillosNo.setText("No");

        jLabel5.setText("Superficie");

        jLabel6.setText("Distancia");

        jsp_distancia.setModel(new javax.swing.SpinnerNumberModel());

        btn_guardarPLaneta.setText("Guardar");
        btn_guardarPLaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarPLanetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_planetaLayout = new javax.swing.GroupLayout(jp_planeta);
        jp_planeta.setLayout(jp_planetaLayout);
        jp_planetaLayout.setHorizontalGroup(
            jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_planetaLayout.createSequentialGroup()
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_planetaLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_planetaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_planetaLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(tf_nombrePlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_planetaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(tf_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_planetaLayout.createSequentialGroup()
                                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsp_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_planetaLayout.createSequentialGroup()
                                        .addComponent(anillosSi)
                                        .addGap(34, 34, 34)
                                        .addComponent(anillosNo))
                                    .addComponent(jsp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_planetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardarPLaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jp_planetaLayout.setVerticalGroup(
            jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_planetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombrePlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsp_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anillosSi)
                    .addComponent(anillosNo))
                .addGap(18, 18, 18)
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_guardarPLaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Planetas", jp_planeta);

        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Crear Astronauta");

        jLabel9.setText("Nacionalidad");

        jLabel10.setText("Sueldo");

        jLabel11.setText("Experiencia");

        tf_experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_experienciaActionPerformed(evt);
            }
        });

        jLabel12.setText("Sexo");

        grupo2.add(sexoF);
        sexoF.setSelected(true);
        sexoF.setText("F");

        grupo2.add(SexoM);
        SexoM.setText("M");

        jLabel13.setText("Peso");

        btn_guardarAstronauta.setText("Guardar");
        btn_guardarAstronauta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarAstronautaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(tf_nombreAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(sexoF)
                                        .addGap(18, 18, 18)
                                        .addComponent(SexoM))
                                    .addComponent(tf_experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardarAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tf_sueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoF)
                    .addComponent(SexoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btn_guardarAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Astronautas", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Naves");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 11, 113, 30));

        jLabel15.setText("Numero Serie");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 49, 79, 26));
        jPanel2.add(tf_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 47, 113, 30));

        jLabel16.setText("Destino");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 72, 26));

        jPanel2.add(jcb_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 174, 33));

        jLabel17.setText("Velocidad");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 75, 29));

        jsp_velocidad.setModel(new javax.swing.SpinnerNumberModel());
        jPanel2.add(jsp_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 75, 31));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Sonda Espacial");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 124, 22));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Tripulada");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 124, 22));

        jLabel20.setText("Material");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 74, 26));

        tf_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialActionPerformed(evt);
            }
        });
        jPanel2.add(tf_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 113, 30));

        jLabel21.setText("Peso");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 75, 29));

        jsp_peso.setModel(new javax.swing.SpinnerNumberModel());
        jPanel2.add(jsp_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 75, 31));

        btn_sonda.setText("Guardar");
        btn_sonda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sondaMouseClicked(evt);
            }
        });
        jPanel2.add(btn_sonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel22.setText("Lugar Despeje");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 74, 26));

        tf_lugarDespeje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lugarDespejeActionPerformed(evt);
            }
        });
        jPanel2.add(tf_lugarDespeje, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 113, 30));

        jLabel23.setText("Astronautas");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 87, 26));

        jPanel2.add(jcb_astronautas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 127, 30));

        jButton1.setText("Anadir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jPanel2.add(jcb_asAgregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, 30));

        btn_tripulada.setText("Guardar");
        btn_tripulada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tripuladaMouseClicked(evt);
            }
        });
        jPanel2.add(btn_tripulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jTabbedPane1.addTab("Naves", jPanel2);

        jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
            }
        ));
        jt_planetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_planetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_planetas);

        btn_listarPlanetas.setText("Listar Planetas");
        btn_listarPlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listarPlanetasMouseClicked(evt);
            }
        });

        btn_ListarAstronautas.setText("Listar Atronautas");
        btn_ListarAstronautas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ListarAstronautasMouseClicked(evt);
            }
        });

        jt_astronautas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
            }
        ));
        jt_astronautas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_astronautasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_astronautas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_listarPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btn_ListarAstronautas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_listarPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ListarAstronautas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Crear Expedicion");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 11, 176, 24));

        jLabel25.setText("Nave");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 54, 60, 30));

        jPanel5.add(jcb_naveExpedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 53, 146, 33));

        btn_Iniciar.setText("Iniciar");
        btn_Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IniciarMouseClicked(evt);
            }
        });
        jPanel5.add(btn_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 118, -1, -1));

        jLabel27.setText("Ida");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 168, 61, 25));
        jPanel5.add(jpb_ida, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 168, 430, 30));

        jLabel28.setText("Regreso");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 244, 50, 20));
        jPanel5.add(jpb_regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 430, 30));

        jTabbedPane1.addTab("Expedicion", jPanel5);

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarMouseClicked
        // TODO add your handling code here:
        try {
            // expedicion.setAvanzar(false);

            Nave nave = (Nave) jcb_naveExpedicion.getSelectedItem();
            double ida = 0;
            double regreso = 0;
            if (nave instanceof SondaEspacial) {
                ida = (((SondaEspacial) nave).polimorfo()[0] * 1000);
                regreso = (((SondaEspacial) nave).polimorfo()[1] * 1000);
            } else if (nave instanceof Tripulada) {
                ida = (((Tripulada) nave).polimorfo()[0] * 1000);
                regreso = (((Tripulada) nave).polimorfo()[1] * 1000);
            }

            jpb_ida.setValue(0);
            jpb_regreso.setValue(0);
            jpb_ida.setMaximum((int) ida);
            jpb_regreso.setMaximum((int) regreso);

            Expedicion expedicion = new Expedicion(true, true, jpb_ida, jpb_regreso, (int) ida, (int) regreso, this);
            System.out.println(ida + " r " + regreso);

            Thread proceso = new Thread(expedicion);
            proceso.start();

            System.out.println("este es ida " + ida + "\nregreso " + regreso);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_IniciarMouseClicked

    private void btn_ListarAstronautasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ListarAstronautasMouseClicked
        // TODO add your handling code here:
        try {
            jt_astronautas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
                    }
            ));
            DefaultTableModel model = (DefaultTableModel) jt_astronautas.getModel();
            for (int i = 0; i < astronautas.size(); i++) {
                String sexo = "";
                if (astronautas.get(i).isSexo() == true) {
                    sexo = "F";
                } else {
                    sexo = "M";
                }

                Object newrow[] = {astronautas.get(i), astronautas.get(i).getNacionalidad(),
                    astronautas.get(i).getSueldo(), astronautas.get(i).getExperiencia(),
                    sexo, astronautas.get(i).getPeso()};
                model.addRow(newrow);
            }// fin del for

            jt_astronautas.setModel(model);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_ListarAstronautasMouseClicked

    private void btn_listarPlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listarPlanetasMouseClicked
        // TODO add your handling code here:
        try {

            jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
                    }
            ));

            DefaultTableModel model = (DefaultTableModel) jt_planetas.getModel();
            for (int i = 0; i < planetas.size(); i++) {
                String anillos = "";
                if (planetas.get(i).isAnillos() == true) {
                    anillos = "Si";
                } else {
                    anillos = "No";
                }

                Object newrow[] = {planetas.get(i), planetas.get(i).getTemperatura(),
                    anillos, planetas.get(i).getSuperficie(), planetas.get(i).getDistancia()};

                model.addRow(newrow);
            }// fin del for

            jt_planetas.setModel(model);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_listarPlanetasMouseClicked

    public void cargarp(){
         try {

            jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
                    }
            ));

            DefaultTableModel model = (DefaultTableModel) jt_planetas.getModel();
            for (int i = 0; i < planetas.size(); i++) {
                String anillos = "";
                if (planetas.get(i).isAnillos() == true) {
                    anillos = "Si";
                } else {
                    anillos = "No";
                }

                Object newrow[] = {planetas.get(i), planetas.get(i).getTemperatura(),
                    anillos, planetas.get(i).getSuperficie(), planetas.get(i).getDistancia()};

                model.addRow(newrow);
            }// fin del for

            jt_planetas.setModel(model);

        } catch (Exception e) {
        }
    }
    
    private void jt_planetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_planetasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1 && evt.isMetaDown()) {
            int este = jt_planetas.getSelectedRow();
            if (este >= 0) {
                pop_opciones.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jt_planetasMouseClicked

    private void btn_tripuladaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tripuladaMouseClicked
        // TODO add your handling code here:
        try {
            int serie;
            Planeta planeta;
            int velocidad;
            String lugarDespeje;

            lugarDespeje = tf_lugarDespeje.getText();
            serie = Integer.parseInt(tf_serie.getText());
            planeta = (Planeta) jcb_planeta.getSelectedItem();
            velocidad = (int) jsp_velocidad.getValue();

            tripuladas.add(new Tripulada(lugarDespeje, serie, planeta, velocidad));
            tripuladas.get(tripuladas.size() - 1).setAstronautas(temporales);

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_naveExpedicion.getModel();
            modelo.addElement(tripuladas.get(tripuladas.size() - 1));
            jcb_naveExpedicion.setModel(modelo);

            System.out.println(tripuladas.get(tripuladas.size() - 1));

            temporales = new ArrayList();
            jcb_astronautas.setModel(new DefaultComboBoxModel());

            tf_lugarDespeje.setText("");
            tf_serie.setText("");
            jsp_velocidad.setValue(0);

            JOptionPane.showMessageDialog(this, "Agregado");

        } catch (Exception e) {
            // e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tripuladaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_asAgregados.getModel();
            modelo.addElement(jcb_astronautas.getSelectedItem());
            jcb_asAgregados.setModel(modelo);

            temporales.add((Astronauta) jcb_astronautas.getSelectedItem());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void tf_lugarDespejeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lugarDespejeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lugarDespejeActionPerformed

    private void btn_sondaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sondaMouseClicked
        // TODO add your handling code here:
        try {
            int serie;
            Planeta planeta;
            int velocidad;
            String material;
            int peso;

            serie = Integer.parseInt("" + tf_serie.getText());
            planeta = (Planeta) jcb_planeta.getSelectedItem();
            velocidad = (int) jsp_velocidad.getValue();
            material = tf_material.getText();
            peso = (int) jsp_peso.getValue();

            sondasEspacials.add(new SondaEspacial(material, peso, serie, planeta, velocidad));

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_naveExpedicion.getModel();
            modelo.addElement(sondasEspacials.get(sondasEspacials.size() - 1));
            jcb_naveExpedicion.setModel(modelo);

            System.out.println(sondasEspacials.get(sondasEspacials.size() - 1));

            tf_serie.setText("");
            jsp_velocidad.setValue(0);
            tf_material.setText("");
            jsp_peso.setValue(0);
            JOptionPane.showMessageDialog(this, "Agregado");

        } catch (Exception e) {
            // e.printStackTrace();
        }
    }//GEN-LAST:event_btn_sondaMouseClicked

    private void tf_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialActionPerformed

    private void btn_guardarAstronautaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarAstronautaMouseClicked
        // TODO add your handling code here:
        String nombre;
        String experiencia;
        String nacionalidad;
        double sueldo;
        int peso;
        boolean sexo = false;
        try {
            if (sexoF.isSelected() == true) {
                sexo = true;
            } else if (SexoM.isSelected() == true) {
                sexo = false;
            }

            nombre = tf_nombreAstronauta.getText();
            experiencia = tf_experiencia.getText();
            nacionalidad = tf_nacionalidad.getText();
            sueldo = Double.parseDouble(tf_sueldo.getText());
            peso = Integer.parseInt(tf_peso.getText());

            astronautas.add(new Astronauta(nombre, nacionalidad, sueldo, experiencia, sexo, peso));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_astronautas.getModel();
            modelo.addElement(astronautas.get(astronautas.size() - 1));
            
            todo.add(astronautas.get(astronautas.size() - 1));
            jcb_astronautas.setModel(modelo);

            System.out.println(astronautas.get(astronautas.size() - 1));

            tf_nombreAstronauta.setText("");
            tf_experiencia.setText("");
            tf_nacionalidad.setText("");
            tf_sueldo.setText("");
            tf_peso.setText("");
            sexoF.setSelected(true);

            JOptionPane.showMessageDialog(this, "Agregado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
    }//GEN-LAST:event_btn_guardarAstronautaMouseClicked

    private void tf_experienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_experienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_experienciaActionPerformed

    private void btn_guardarPLanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarPLanetaMouseClicked
        // TODO add your handling code here:
        String nombre;
        String superficie;
        boolean anillos = false;
        int temperatura;
        int distancia;
        try {

            if (anillosSi.isSelected() == true) {
                anillos = true;
            } else if (anillosNo.isSelected() == true) {
                anillos = false;
            }

            nombre = tf_nombrePlaneta.getText();
            superficie = tf_superficie.getText();
            temperatura = (int) jsp_temperatura.getValue();
            distancia = (int) jsp_distancia.getValue();

            planetas.add(new Planeta(nombre, temperatura, anillos, superficie, distancia));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_planeta.getModel();
            modelo.addElement(planetas.get(planetas.size() - 1));
            
            todo.add(planetas.get(planetas.size() - 1));
            jcb_planeta.setModel(modelo);

            System.out.println(planetas.get(planetas.size() - 1));

            tf_nombrePlaneta.setText("");
            tf_superficie.setText("");
            jsp_temperatura.setValue(0);
            jsp_distancia.setValue(0);
            anillosSi.setSelected(true);
            JOptionPane.showMessageDialog(this, "Agregado");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_guardarPLanetaMouseClicked

    private void jmi_eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminaActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_planetas.getSelectedRow();

            planetas.remove(este);
            DefaultComboBoxModel modelO = (DefaultComboBoxModel) jcb_planeta.getModel();
            modelO.removeElementAt(este);
            jcb_planeta.setModel(modelO);

            jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
                    }
            ));

            DefaultTableModel model = (DefaultTableModel) jt_planetas.getModel();
            for (int i = 0; i < planetas.size(); i++) {
                String anillos = "";
                if (planetas.get(i).isAnillos() == true) {
                    anillos = "Si";
                } else {
                    anillos = "No";
                }

                Object newrow[] = {planetas.get(i), planetas.get(i).getTemperatura(),
                    anillos, planetas.get(i).getSuperficie(), planetas.get(i).getDistancia()};

                model.addRow(newrow);
            }// fin del for

            jt_planetas.setModel(model);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_eliminaActionPerformed

    private void jt_astronautasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_astronautasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1 && evt.isMetaDown()) {
            int este = jt_astronautas.getSelectedRow();
            if (este >= 0) {
                pop_opcionesA.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jt_astronautasMouseClicked

    private void jmi_EliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_EliminarAActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            astronautas.remove(este);
            DefaultComboBoxModel modelO = (DefaultComboBoxModel) jcb_astronautas.getModel();
            modelO.removeElement(este);
            jcb_astronautas.setModel(modelO);
            
            
            jt_astronautas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
                    }
            ));
            DefaultTableModel model = (DefaultTableModel) jt_astronautas.getModel();
            for (int i = 0; i < astronautas.size(); i++) {
                String sexo = "";
                if (astronautas.get(i).isSexo() == true) {
                    sexo = "F";
                } else {
                    sexo = "M";
                }

                Object newrow[] = {astronautas.get(i), astronautas.get(i).getNacionalidad(),
                    astronautas.get(i).getSueldo(), astronautas.get(i).getExperiencia(),
                    sexo, astronautas.get(i).getPeso()};
                model.addRow(newrow);
            }// fin del for

            jt_astronautas.setModel(model);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_EliminarAActionPerformed

    private void jmi_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nombreActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            Astronauta a = (Astronauta) jt_astronautas.getValueAt(este, 0);
            
            astronautas.get(este).setNombre(JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre"));
            cargar();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_nombreActionPerformed

    private void jmi_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nacionalidadActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            Astronauta a = (Astronauta) jt_astronautas.getValueAt(este, 0);
            
            astronautas.get(este).setNacionalidad(JOptionPane.showInputDialog(this, "Ingrese la nueva nacionalidad"));
            cargar();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_nacionalidadActionPerformed

    private void jmi_sueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_sueldoActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            Astronauta a = (Astronauta) jt_astronautas.getValueAt(este, 0);
            
            astronautas.get(este).setSueldo(Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese el nuevo sueldo")));
            cargar();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_sueldoActionPerformed

    private void jmi_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pesoActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            Astronauta a = (Astronauta) jt_astronautas.getValueAt(este, 0);
            
            astronautas.get(este).setPeso(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el nuevo peso")));
            cargar();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_pesoActionPerformed

    private void jmi_experienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_experienciaActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_astronautas.getSelectedRow();
            Astronauta a = (Astronauta) jt_astronautas.getValueAt(este, 0);
            
            astronautas.get(este).setExperiencia(JOptionPane.showInputDialog(this, "Ingrese la experiencia: "));
            cargar();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_experienciaActionPerformed

    private void jmi_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nombrePActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_planetas.getSelectedRow();
            Planeta a = (Planeta) jt_planetas.getValueAt(este, 0);
            
            planetas.get(este).setNombre(JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre: "));
            cargarp();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_nombrePActionPerformed

    private void jmi_temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_temperaturaActionPerformed
        // TODO add your handling code here:
         try {
            int este = jt_planetas.getSelectedRow();
            Planeta a = (Planeta) jt_planetas.getValueAt(este, 0);
            
            planetas.get(este).setTemperatura(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la nueva temperatura: ")));
            cargarp();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_temperaturaActionPerformed

    private void jmi_superficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_superficieActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_planetas.getSelectedRow();
            Planeta a = (Planeta) jt_planetas.getValueAt(este, 0);
            
            planetas.get(este).setSuperficie(JOptionPane.showInputDialog(this, "Ingrese la nueva superficie "));
            cargarp();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_superficieActionPerformed

    private void jmi_distanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_distanciaActionPerformed
        // TODO add your handling code here:
        try {
            int este = jt_planetas.getSelectedRow();
            Planeta a = (Planeta) jt_planetas.getValueAt(este, 0);
            
            planetas.get(este).setDistancia(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la nueva distancia: ")));
            cargarp();
            System.out.println(a.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_distanciaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
           JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showSaveDialog(this); //finciona

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                administrador a = new administrador(jfc.getSelectedFile().getPath()+".idm");
                a.cargar();
                JOptionPane.showMessageDialog(this, "Guardado");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void cargar(){
         try {
            
           
            jt_astronautas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
                    }
            ));
            DefaultTableModel model = (DefaultTableModel) jt_astronautas.getModel();
            for (int i = 0; i < astronautas.size(); i++) {
                String sexo = "";
                if (astronautas.get(i).isSexo() == true) {
                    sexo = "F";
                } else {
                    sexo = "M";
                }

                Object newrow[] = {astronautas.get(i), astronautas.get(i).getNacionalidad(),
                    astronautas.get(i).getSueldo(), astronautas.get(i).getExperiencia(),
                    sexo, astronautas.get(i).getPeso()};
                model.addRow(newrow);
            }// fin del for

            jt_astronautas.setModel(model);
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SexoM;
    private javax.swing.JRadioButton anillosNo;
    private javax.swing.JRadioButton anillosSi;
    private javax.swing.JButton btn_Iniciar;
    private javax.swing.JButton btn_ListarAstronautas;
    private javax.swing.JButton btn_guardarAstronauta;
    private javax.swing.JButton btn_guardarPLaneta;
    private javax.swing.JButton btn_listarPlanetas;
    private javax.swing.JButton btn_sonda;
    private javax.swing.JButton btn_tripulada;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_asAgregados;
    private javax.swing.JComboBox<String> jcb_astronautas;
    private javax.swing.JComboBox<String> jcb_naveExpedicion;
    private javax.swing.JComboBox<String> jcb_planeta;
    private javax.swing.JMenuItem jmi_EliminarA;
    private javax.swing.JMenuItem jmi_distancia;
    private javax.swing.JMenuItem jmi_elimina;
    private javax.swing.JMenuItem jmi_experiencia;
    private javax.swing.JMenuItem jmi_nacionalidad;
    private javax.swing.JMenuItem jmi_nombre;
    private javax.swing.JMenuItem jmi_nombreP;
    private javax.swing.JMenuItem jmi_peso;
    private javax.swing.JMenuItem jmi_sueldo;
    private javax.swing.JMenuItem jmi_superficie;
    private javax.swing.JMenuItem jmi_temperatura;
    private javax.swing.JPanel jp_planeta;
    private javax.swing.JProgressBar jpb_ida;
    private javax.swing.JProgressBar jpb_regreso;
    private javax.swing.JSpinner jsp_distancia;
    private javax.swing.JSpinner jsp_peso;
    private javax.swing.JSpinner jsp_temperatura;
    private javax.swing.JSpinner jsp_velocidad;
    private javax.swing.JTable jt_astronautas;
    private javax.swing.JTable jt_planetas;
    private javax.swing.JPopupMenu pop_opciones;
    private javax.swing.JPopupMenu pop_opcionesA;
    private javax.swing.JRadioButton sexoF;
    private javax.swing.JTextField tf_experiencia;
    private javax.swing.JTextField tf_lugarDespeje;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombreAstronauta;
    private javax.swing.JTextField tf_nombrePlaneta;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_serie;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_superficie;
    // End of variables declaration//GEN-END:variables

    ArrayList<Planeta> planetas = new ArrayList();
    ArrayList<Astronauta> astronautas = new ArrayList();
    ArrayList<SondaEspacial> sondasEspacials = new ArrayList();
    ArrayList<Tripulada> tripuladas = new ArrayList();

    ///
    ArrayList<Astronauta> temporales = new ArrayList();
    
    ArrayList<Object> todo = new ArrayList();
    //  Expedicion expedicion;
}
